name: CI

on:
  pull_request:
    branches:
      - "main"

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
  
      - name: Build docker image
        run: |
          docker compose build
          docker compose up -d

      - name: composer install
        run: docker compose exec -T app bash -c "composer install"

      - name: laravel pint
        run: docker compose exec -T app bash -c "./vendor/bin/pint"

      - name: PHPStan
        run: docker compose exec -T app bash -c "./vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=-1"

      - name: test 
        run: docker compose exec -T app bash -c "./vendor/bin/phpunit"
